blank_issues_enabled: false
contact_links:
  - name: Twitter
    about: その他､ GitHub上では問い合わせ出来ない問題等
    url: https://twitter.com/intent/tweet?text=%40Hidemaru_OwO%0D%0AAwesome-HelloWorld%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%0D%0A%0D%0A
