name: ASM_amd64_linux 1


on:
  push:
    paths:
      - '.github/workflows/asm_amd64_linux-1.yml'
      - 'asm_amd64_linux/hello_world_1/**'
  workflow_dispatch:

jobs:
  make:
    name: Make
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install lld and nasm
        run: sudo apt-get install -y lld nasm
        
      - name: Build
        working-directory: asm_amd64_linux/hello_world_1/
        run: make

      - name: Hello World!
        run: ./asm_amd64_linux/hello_world_1/helloasm
