name: Java 1

on:
  push:
    paths:
      - '.github/workflows/java-1.yml'
      - 'java/hello_world_1/**'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Compile
        run: |
          javac java/hello_world_1/main.java

      - name: Hello World!!
        working-directory: java/hello_world_1/
        run: java main
