name: Kotlin 2

on:
  push:
    paths:
      - '.github/workflows/kotlin-2.yml'
      - 'kotlin/hello_world_2/**'
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: kotlin-2-${{ hashFiles('kotlin/hello_world_2/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: kotlin-2-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build
        working-directory: kotlin/hello_world_2/
        run: ./gradlew build

      - name: Hello World!
        working-directory: kotlin/hello_world_2/
        run: ./gradlew run
