name: Kubernetes 1

on:
  push:
    paths:
      - '.github/workflows/kubernetes-1.yml'
      - 'kubernetes/main.sh'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Hello World!!
        run: bash -xc kubernetes/hello_world_1/main.sh
