name: Malbolge 1

on:
  push:
    paths:
      - '.github/workflows/malbolge-1.yml'
  workflow_dispatch:


jobs:
  run:
    name: Malbolge 1
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile Malbolge
        working-directory: malbolge
        run: |
          sudo apt-get install -y gcc
          gcc malbolge.c

      - name: Run
        working-directory: malbolge
        run: ./a.out hello_world_1/wikipedia.sample
