name: Nim 1

on:
  push:
    paths:
      - ".github/workflows/nim-1.yaml"
      - "nim/hello_world_1/**"
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1

      - name: Test
        working-directory: nim/hello_world_1/
        run: testament p 'tests/*.nim'

      - name: Compile
        working-directory: nim/hello_world_1/
        run: nim c -d:release src/main.nim

      - name: Hello World!!
        working-directory: nim/hello_world_1/src/
        run: ./main
