name: Python 8

on:
  push:
    paths:
      - '.github/workflows/python-8.yml'
      - 'python/hello_world_8/**'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup latest Python
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'

      - name: Hello World!!
        working-directory: python/hello_world_8/
        run: ./run.sh
