name: Python 2

on:
  push:
    paths:
      - '.github/workflows/python-2.yml'
      - 'python/hello_world_2/**'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup latest Python
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'

      - name: Hello World!!
        run: python3 python/hello_world_2/main.py
