name: Python 4

on:
  push:
    paths:
      - '.github/workflows/python-4.yml'
      - 'python/hello_world_4/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup latest Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Hello World!!
        run: python3 ./python/hello_world_4/main.py
